### ISSUE TITLE
Creation of Policy

### ISSUE THREAD

**Issue by envisionblockchainpm** [hashgraph/guardian#278] opened 2021-12-31 17:24 UTC
USER STORY:
As a Root Authority User I want to see the Verra / REDD / APD Policy. 

DOD:
- Policy created and deployed to MAIN Branch

**Comment by envisionblockchainpm** [comment] 2022-01-18 16:07
Assigning to you @Pyatakov for estimating. Please estimate. Adding to this Sprint as requested and this has been put into the Verra Development Epic as requested.

**Comment by anvabr** [comment] 2022-01-20 14:45
Closed as duplicate of the 'prepare Demo' issue

**Closed** 2022-01-20 14:45 UTC
Labels: technical task
