### ISSUE TITLE
Progress bar screen disappeared for schemas.

### ISSUE THREAD

**Issue by kirill-tolochko** [hashgraph/guardian#2047] opened 2023-04-24 14:09 UTC
### Problem description

If user tries upload/publish any schema, he doesn't see progress bar of uploading/publishing anymore.

### Step to reproduce
1. Create schema and save it / or import schema / or publish existing schema

### Expected behavior
Progress bar appeared, after that list if schemas are updates, new schema is presented

https://images.zenhubusercontent.com/416030891/06a1a9f5-3e6c-41be-9c39-024a393278b4/screen_recording_2023_04_24_at_9_56_49_am.mov

### Actual behavior
There is no progress bar, list of schemas aren't updated, new schema isn't presented. To see new schema/ new status of schema (draft -> published) you need to update the page.

**Comment by prernaadev01** [comment] 2023-04-24 17:50
duplicate of #2046 ticket

**Closed** 2023-04-25 13:28 UTC
Labels: bug, duplicate
