### ISSUE TITLE
Plug-able architecture fo FastMQ

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#216] opened 2021-12-17 17:34 UTC
### Problem

Currently there is no easy way to implement extensions (Plug-ins) to the FastMQ functionality which limits its usefulness for production deployment.

### Solution

@voycey team plans to implement integration with Google PubSub and the Google PubSub emulator (for local use), the implementation would look like:

- Create an interface for the message broker that includes: `/mrv endpoint (publish)`
- Modify FastMQ to extend this interface and create package message-broker-fastmq and modify package.json to keep default setup
- Create new package message-broker-pubsub
- Look at possibly implementing this via webpack (https://webpack.js.org/plugins/copy-webpack-plugin/) to allow for easy customisation
- PubSubEmulator Docker Container would be created for local development (named message-broker)
- Environment variables for production setup to connect to Live PubSub vs PubSubEmulator

This setup would keep the current default setup but provide a plugin architecture to allow for new message queue plugins to be built according to requirements (AWS SQS & Redis for example).

**Comment by voycey** [comment] 2022-01-18 02:16
This should be "plugable Archtecture for Message Queue Component" - the idea is to be able to give an easy way to replace FastMQ with whatever queue system is required whilst leaving FastMQ as the default for an install to allow for fast local development.

FastMQ will not be production ready without TLS (even authentication will not be enough as it would be transmitting unencrypted information across networks)

**Comment by prernaadev01** [comment] 2022-03-04 15:23
Duplicate of #215

**Comment by prernaadev01** [comment] 2022-03-23 17:45
This ticket is also cancelled as we have cancelled #215

**Closed** 2022-03-23 17:46 UTC
Labels: duplicate, enhancement, invalid
