### ISSUE TITLE
Field data type for the policy blocks

### ISSUE THREAD

**Issue by sergmetelin** [hashgraph/guardian#326] opened 2022-01-18 15:50 UTC
### Problem

- As a policy creator I need to be able to request the upload of the media files as part of data collection from the policy participants
- As a policy user, I need to be able to submit media files as a part of the form submission
- As an auditor, I need to be able to view the media files submitted as a part of the form submission

### Solution

- Add a new data type field "Media file" (?)
- It should upload a file to a storage engine (IPFS/nft.storage for now, should be decoupled)

**Comment by envisionblockchainpm** [comment] 2022-01-19 15:03
This ticket is a Duplicate of this ticket which is in progress. Closing.  Create File Upload Functionality for Schemas and Forms#279 . We transferred @sergmetelin wording in this ticket and added it to #279.

**Closed by envisionblockchainpm** 2022-01-19 15:03 UTC
Labels: enhancement
