### ISSUE TITLE
Implement basic CI/CD

### ISSUE THREAD

**Issue by sergmetelin** [hashgraph/guardian#4] opened 2021-10-14 17:22 UTC
The CI should cover linting as well as unit tests at a minimum.

**Comment by envisionblockchainpm** [comment] 2021-11-15 16:37
This is another Duplicate of Issue 40. Closing with a Link:

https://app.zenhub.com/workspaces/guardian-618c27c08661c0001461263a/issues/hashgraph/guardian/40

**Comment by anvabr** [comment] 2021-11-25 10:18
Note: Reopened the issue and changed its focus on implementation of the CI (budges are covered in the #40).

### Requirements
CI/CD is a common 'best practice'  to organising software development. This ticket requires the implementation of Github Actions workflow to be triggered every time a commit to main has occurred.

### DOD
The workflow described in the Acceptance Criteria section below is executed automatically triggered by the change in the main repo.

### Acceptance Criteria

Github Actions workflow exists in the <REPO>/.github/workflows/ci.yml containing the following logic which gets executed on every commit to MAIN:
- Codebase is "linted", i.e. checked and formatted by the lint utility
- Repo is tagged
- Software artefacts are built and published (where appropriate)
- Unit tests are executed and the results are recorded

**Comment by envisionblockchainpm** [comment] 2021-12-03 14:49
@danielnorkin @sergmetelin This was just QA Tested and complete, moving to Close.

**Closed** 2021-12-03 14:49 UTC
Labels: enhancement, community
