### ISSUE TITLE
Retraction Definition & Architecture

### ISSUE THREAD

**Issue by dubgeis** [hashgraph/guardian#945] opened 2022-06-01 12:33 UTC
As a user I want to correct an error of a minted token or issued VC where a token is not in a state of reversal but issuance in error.

**Comment by prernaadev01** [comment] 2022-12-08 17:02
This ticket is duplicate of [#838](https://github.com/hashgraph/guardian/issues/838)

**Closed** 2024-09-03 20:49 UTC
Labels: duplicate
