### ISSUE TITLE
AggregateBlock return `Bad token id`

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#832] opened 2022-05-02 08:29 UTC
### Problem description
This is happening on V2. 

Maybe caused by this - https://github.com/hashgraph/guardian/blob/main/guardian-service/src/policy-engine/blocks/aggregate-block.ts#L54

I check the setting for AggregateBlock it only have rule and threshold, Token is only in Mint block? But now sure why it works in v1.2.1 but break after change to 2.0

![image](https://user-images.githubusercontent.com/1183138/166206540-8b84bcf4-8be4-4727-8a6d-dcff750e305b.png)

Look like the piece of code above is only validation purpose, I commented out this validation and mrv aggregation working and token mint also work. code history show that this already there for 7 months, Could you please review if there any change in v2 cause the issue

### Step to reproduce

- Setup the policy with AggregateBlock
- Create MRV

**Comment by anvabr** [comment] 2022-05-04 14:00
@samuraitruong Thank you for posting this, this is indeed a bug. We are adding a significant amount of functionality on aggregation in the new release (#53), the offending section of code has been re-worked and the issue is fixed in the development branches. How urgently do you need the fix? We could make a hotfix if this is urgent, but if possible I'd rather delay this until the next release (currently target - 17th of May)?

**Closed** 2022-05-06 16:35 UTC
Labels: bug, community
