### ISSUE TITLE
UX Register

### ISSUE THREAD

**Issue by blockchain-biopharma** [hashgraph/guardian#258] opened 2021-12-29 17:46 UTC
## Requirement
As a Guardian User, when asking for the DID, submitting the VC (if not, Create DID), then its going to be understanding (list or Matrix), understand the schema of the data and the policy that the data is following (How do we validate if this data has been validated by the 3rd Party Guardian or Other Data Source)?

We have to know that the data is good, and someone is not sending the data to cause some type of negative consequence. It has to be good data. 

What role does this data play within the current Guardian Policy, is it a single point of failure? If it is, determine Error Code or Denominate Back-up procedure. 

## Pre Requisite
- Discovery Session with Hedera Team

## Definition of Done
- Need @anvabr and @Pyatakov help to define this, this is TBD. @danielnorkin

**Comment by prernaadev01** [comment] 2022-12-08 16:58
This ticket is duplicate of [#1515](https://github.com/hashgraph/guardian/issues/1515)

**Closed** 2024-03-15 14:22 UTC
Labels: duplicate
