### ISSUE TITLE
List UIUX Design and Changes

### ISSUE THREAD

**Issue by danielnorkin** [hashgraph/guardian#42] opened 2021-11-11 15:35 UTC
As a user of the Guardian reference implementation demo, I want to be able to see the changes made to Issue #41 on the User Interface. 

DOD: Design prepared for the Development Team that covers this functionality, i.e. the Mockup itself. 

Acceptance Criteria: Designer creates these Screens and Obtains Approval from the Stakeholder (Matt at DOVU).

Whoever is creating the Policy needs to be able to define the lists and their values. 
Whoever is Filling out the Form needs to be able to select something on that list.

**Comment by envisionblockchainpm** [comment] 2021-11-15 16:45
This is for the UI / UX Designer.

**Comment by envisionblockchainpm** [comment] 2021-11-19 14:55
The next step is for @danielnorkin

**Comment by anvabr** [comment] 2021-11-25 12:30
Duplicate of #120 and #121

**Closed** 2021-11-25 12:30 UTC
Labels: technical task
